import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('app keeps the multipage shell without legacy chrome', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')

  assert.doesNotMatch(appSource, /Cursor/)
  assert.doesNotMatch(appSource, /FilmGrain/)
  assert.doesNotMatch(appSource, /Marquee/)
  assert.match(appSource, /lazy\(\(\)\s*=>\s*import/)
  assert.match(appSource, /Suspense/)
  assert.match(appSource, /path="proyectos"/)
  assert.match(appSource, /path="proyectos\/:slug"/)
  assert.match(appSource, /path="studio"/)
  assert.match(appSource, /path="contacto"/)
  assert.match(appSource, /path="\*"/)
})

test('home page is rebuilt around a pinned reel and integrated end frame', () => {
  const homeSource = readFileSync(new URL('../src/pages/HomePage.jsx', import.meta.url), 'utf8')

  assert.match(homeSource, /HomeReel/)
  assert.match(homeSource, /HomeClientBand/)
  assert.match(homeSource, /HomeEndFrame/)
  assert.doesNotMatch(homeSource, /HomeHeroStage/)
  assert.doesNotMatch(homeSource, /HomeMediaFlow/)
  assert.doesNotMatch(homeSource, /HomeClosingCta/)
  assert.doesNotMatch(homeSource, /from '\.\.\/components\/Hero\/Hero'/)
  assert.doesNotMatch(homeSource, /from '\.\.\/components\/Marquee\/Marquee'/)
  assert.doesNotMatch(homeSource, /from '\.\.\/components\/ProjectsPreview\/ProjectsPreview'/)
})

test('loader remains a full wordmark reveal without progress line chrome', () => {
  const loaderSource = readFileSync(new URL('../src/components/Loader/Loader.jsx', import.meta.url), 'utf8')
  const loaderCss = readFileSync(new URL('../src/components/Loader/Loader.css', import.meta.url), 'utf8')

  assert.match(loaderSource, /siteContent\.brand\.name/)
  assert.match(loaderSource, /siteContent\.hero\.eyebrow/)
  assert.match(loaderSource, /siteContent\.hero\.primaryCta\.label/)
  assert.doesNotMatch(loaderSource, /loader__line/)
  assert.doesNotMatch(loaderSource, />M4</)
  assert.match(loaderCss, /\.loader__view/)
})

test('home reel exposes pinned frames and sequential color comparison cases', () => {
  const reelSource = readFileSync(new URL('../src/components/HomeReel/HomeReel.jsx', import.meta.url), 'utf8')
  const reelCss = readFileSync(new URL('../src/components/HomeReel/HomeReel.css', import.meta.url), 'utf8')
  const comparisonCss = readFileSync(new URL('../src/components/ComparisonSlider/ComparisonSlider.css', import.meta.url), 'utf8')

  assert.match(reelSource, /home-reel__sticky/)
  assert.match(reelSource, /home-reel__title-card/)
  assert.match(reelSource, /siteContent\.colorization\.title/)
  assert.match(reelSource, /siteContent\.colorization\.reels/)
  assert.match(reelSource, /home-reel__color-stage/)
  assert.match(reelSource, /home-reel__color-wash/)
  assert.match(reelSource, /home-reel__comparison-stage/)
  assert.match(reelSource, /home-reel__comparison-entry/)
  assert.match(reelSource, /home-reel__comparison-track/)
  assert.match(reelSource, /home-reel__comparison-slide/)
  assert.match(reelSource, /home-reel__comparison-details/)
  assert.match(reelSource, /ComparisonSlider/)
  assert.match(reelSource, /home-reel-stagechange/)
  assert.match(reelSource, /item=\{reel\}/)
  assert.match(reelSource, /reel\.client/)
  assert.match(reelSource, /reel\.year/)
  assert.match(reelSource, /reel\.tags\.map/)
  assert.match(reelSource, /<video/)
  assert.match(reelSource, /autoPlay/)
  assert.match(reelSource, /muted/)
  assert.match(reelSource, /loop/)
  assert.match(reelSource, /playsInline/)
  assert.match(reelSource, /showcaseProjects\.slice\(0,\s*4\)/)
  assert.match(reelSource, /const TITLE_FADE_OUT_START = 0\.38/)
  assert.match(reelSource, /const TITLE_FADE_OUT_END = 0\.58/)
  assert.match(reelSource, /const TITLE_FADE_IN_START = 0\.48/)
  assert.match(reelSource, /const TITLE_FADE_IN_END = 0\.74/)
  assert.match(reelSource, /const COLOR_TITLE_DROP_END = 0\.56/)
  assert.match(reelSource, /const COLOR_TITLE_FILL_START = 0\.66/)
  assert.match(reelSource, /--grade-title-fill-opacity/)
  assert.match(reelSource, /const COLOR_TITLE_SUPPRESS_START =/)
  assert.match(reelSource, /const COLOR_TITLE_SUPPRESS_END =/)
  assert.match(reelSource, /const COLOR_METADATA_REVEAL_START = 0\.06/)
  assert.match(reelSource, /const COLOR_METADATA_REVEAL_END = 0\.42/)
  assert.match(reelSource, /const REEL_SETTLE_HOLD = 0\.58/)
  assert.match(reelSource, /const COLOR_COMPARISON_FIRST_HOLD = 1\.04/)
  assert.match(reelSource, /const COLOR_COMPARISON_CENTER_HOLD = 0\.98/)
  assert.match(reelSource, /const COLOR_COMPARISON_FINAL_HOLD = 1\.1/)
  assert.match(reelSource, /const COLOR_COMPARISON_FIRST_HOLD_END =/)
  assert.match(reelSource, /const COLOR_COMPARISON_SECOND_HOLD_END =/)
  assert.match(reelSource, /const COLOR_COMPARISON_FINAL_HOLD_END =/)
  assert.match(reelSource, /'--reel-frames': reducedMotion \? 1 : reelProjects\.length \+ REEL_SETTLE_HOLD \+ COLOR_STAGE_TRANSITION_COUNT/)
  assert.match(reelSource, /querySelector\('\.home-reel__color-title-shell'\)/)
  assert.match(reelSource, /const titleEntryDistance = Math\.max\(/)
  assert.match(reelSource, /const comparisonStageOpacity = colorRaw > 0 \? 1 : 0/)
  assert.doesNotMatch(reelSource, /const titleDropVisible =/)
  assert.match(reelSource, /normalizeRange\(\s*localProgress,\s*TITLE_FADE_IN_START,\s*TITLE_FADE_IN_END,\s*\)/)
  assert.match(reelSource, /scrollTrigger:\s*\{[\s\S]*scrub:\s*true/)
  assert.match(reelCss, /\.home-reel__frame/)
  assert.match(reelCss, /\.home-reel__band/)
  assert.match(reelCss, /\.home-reel__color-title/)
  assert.match(reelCss, /\.home-reel__color-title-shell[\s\S]*padding-block:\s*0\.14em 0\.18em;/)
  assert.match(reelCss, /\.home-reel__color-title-shell[\s\S]*justify-items:\s*center;/)
  assert.match(reelCss, /\.home-reel__color-title-copy[\s\S]*padding-block:\s*0\.14em 0\.18em;/)
  assert.match(reelCss, /\.home-reel__color-title-copy[\s\S]*overflow:\s*visible;/)
  assert.match(reelCss, /\.home-reel__color-title-copy[\s\S]*grid-area:\s*1\s*\/\s*1;/)
  assert.match(reelCss, /\.home-reel__color-title-copy[\s\S]*0 0 14px color-mix\(in srgb, var\(--text\) 4%, transparent\)/)
  assert.match(reelCss, /\.home-reel__color-title-copy--fill[\s\S]*0 0 18px color-mix\(in srgb, var\(--text\) 4%, transparent\)/)
  assert.match(reelCss, /\.home-reel__color-title-copy--fill[\s\S]*position:\s*relative;/)
  assert.match(reelCss, /--grade-title-fill-opacity:/)
  assert.match(reelCss, /\.home-reel__color-title-copy--fill[\s\S]*opacity:\s*var\(--grade-title-fill-opacity\);/)
  assert.match(reelCss, /\.home-reel__color-wash/)
  assert.match(reelCss, /\.home-reel__comparison-stage/)
  assert.match(reelCss, /\.home-reel__comparison-entry/)
  assert.match(reelCss, /\.home-reel__comparison-track/)
  assert.match(reelCss, /\.home-reel__comparison-slide/)
  assert.match(reelCss, /\.home-reel__comparison-details/)
  assert.doesNotMatch(reelCss, /\.home-reel__comparison-details[\s\S]*transition:/)
  assert.match(reelCss, /\.home-reel__comparison-device[\s\S]*width:\s*min\(100%, var\(--comparison-surface-width\)\);/)
  assert.match(reelCss, /--grade-title-rest-opacity:/)
  assert.match(reelCss, /--comparison-details-opacity:/)
  assert.match(reelCss, /--comparison-stage-scale:\s*1;/)
  assert.match(reelCss, /--comparison-stage-rotate:\s*0deg;/)
  assert.match(reelCss, /@media \(max-width: 1080px\)\s*\{[\s\S]*\.home-reel__comparison-stage-inner[\s\S]*width:\s*min\(100%, 44rem\);/)
  assert.match(comparisonCss, /@media \(max-width: 560px\)\s*\{[\s\S]*\.comparison-slider__handle[\s\S]*--comparison-handle-size:\s*clamp\(2\.35rem,\s*9vw,\s*2\.7rem\);/)
  assert.match(reelCss, /--title-step:/)
  assert.match(reelCss, /\.home-reel__title-window/)
  assert.match(reelCss, /--title-opacity:/)
  assert.match(reelCss, /--title-blur:/)
  assert.match(reelCss, /\.home-reel__title-card[\s\S]*filter:\s*blur\(var\(--title-blur\)\)/)
  assert.match(reelCss, /min-height:\s*calc\(var\(--reel-frames\)\s*\*\s*100dvh\)/)
  assert.match(reelCss, /height:\s*100dvh/)
  assert.doesNotMatch(reelCss, /100svh/)
  assert.doesNotMatch(reelSource, /home-reel__color-reel/)
  assert.doesNotMatch(reelCss, /\.home-reel__color-reel/)
  assert.doesNotMatch(reelSource, /home-reel__brand-band/)
  assert.doesNotMatch(reelSource, /BRAND_BAND_FADE_START/)
})

test('comparison slider keeps comparison videos synchronized and exposes editorial labels', () => {
  const comparisonSource = readFileSync(new URL('../src/components/ComparisonSlider/ComparisonSlider.jsx', import.meta.url), 'utf8')

  assert.match(comparisonSource, /beforeLabel = 'Antes'/)
  assert.match(comparisonSource, /afterLabel = 'Despues'/)
  assert.match(comparisonSource, /querySelector\('video'\)/)
  assert.match(comparisonSource, /const syncFollowerToLeader =/)
  assert.match(comparisonSource, /leader\.addEventListener\('timeupdate', syncTiming\)/)
  assert.match(comparisonSource, /leader\.addEventListener\('play', syncPlayback\)/)
  assert.match(comparisonSource, /follower\.currentTime = leader\.currentTime/)
})

test('home client band renders a continuous loop before the closing frame', () => {
  const bandSource = readFileSync(new URL('../src/components/HomeClientBand/HomeClientBand.jsx', import.meta.url), 'utf8')
  const bandCss = readFileSync(new URL('../src/components/HomeClientBand/HomeClientBand.css', import.meta.url), 'utf8')

  assert.match(bandSource, /home-client-band/)
  assert.match(bandSource, /home-client-band__group/)
  assert.match(bandSource, /siteContent\.clients/)
  assert.doesNotMatch(bandSource, /showcaseProjects/)
  assert.match(bandCss, /\.home-client-band__track/)
  assert.match(bandCss, /\.home-client-band__group/)
  assert.match(bandCss, /animation:\s*home-client-band-scroll/)
  assert.match(bandCss, /42s linear infinite/)
})

test('home end frame integrates contact and lower support links without the old client list', () => {
  const endSource = readFileSync(new URL('../src/components/HomeEndFrame/HomeEndFrame.jsx', import.meta.url), 'utf8')
  const endCss = readFileSync(new URL('../src/components/HomeEndFrame/HomeEndFrame.css', import.meta.url), 'utf8')
  const contactSource = readFileSync(new URL('../src/pages/ContactPage.jsx', import.meta.url), 'utf8')

  assert.match(endSource, /siteContent\.contact\.title/)
  assert.match(endSource, /TextSwap/)
  assert.match(contactSource, /contact\.title/)
  assert.match(endSource, /home-end__footer-links/)
  assert.match(endCss, /\.home-end__title-label/)
  assert.match(endCss, /\.home-end__title-label[\s\S]*text-shadow:/)
  assert.match(endCss, /\.home-end__title:is\(:hover,\s*:focus-visible\)\s+\.text-swap__layer[\s\S]*transition-delay:/)
  assert.match(endCss, /\.home-end[\s\S]*background:\s*var\(--bg\)/)
  assert.match(endCss, /min-height:\s*100dvh/)
  assert.doesNotMatch(endCss, /100svh/)
  assert.doesNotMatch(endCss, /\.home-end[\s\S]*background:\s*#020202/)
  assert.doesNotMatch(endSource, /home-end__top-list/)
})

test('studio page keeps a structural heading even with the manifesto-led layout', () => {
  const studioSource = readFileSync(new URL('../src/pages/StudioPage.jsx', import.meta.url), 'utf8')

  assert.match(studioSource, /<h1 className="studio__sr-title">/)
})
